### ISSUE TITLE
_data/data.js > pagination en dur dans la requête GraphQL

### ISSUE THREAD

**Issue by yann-yinn** [fireblogcms/eleventy-starter-fireblog#10]
La pagination semble en dur dans la requêtre Graphql
```
  posts(last: 20, before: "${before}"){
```

mais en même temps il y a une variable "recordsPerQuery" qui vaut 100, qui semble utilisé pour déterminer si on est à la fin de la pagination ou pas ?

**Comment by bertrandkeller** [comment]
`recordsPerQuery`, j'ai trouvé ça dans un exemple, c'est je crois une limitation de graphQL pour lister 100 par 100, je sais plus si mon code utilise encore ce procéder.

Oui, il semble qu'on ne devait pas utiliser la pagination dans l'appel graphQL, mais tout charger d'une coup.

**Comment by yann-yinn** [comment]
j'ai viré la limite puisque sinon seul 20 posts pouvaient s'afficher. Je récupère 1000 posts d'un coup sans while pour le moment et puis zou.
