### ISSUE TITLE
HTML metadata issues

### ISSUE THREAD

**Issue by yann-yinn** [fireblogcms/eleventy-starter-fireblog#3]
*Reproduce* :

- `npm run build`
- `serve _site` (https://www.npmjs.com/package/serve)
- go to `http://localhost:5000`

.env file content : 

```sh
# required
FIREBLOG_GRAPHQL_ENDPOINT = https://api.fireblogcms.com/graphql/blog/5e0cc6b2c96420000444d376
# required
SITE_URL = http://localhost:5000
# optionnal
GOOGLE_ANALYTICS_TRACKING_ID = abc
# optionnal, to render all medias embeded with iframely
IFRAMELY_API_KEY = abc
```
---

- [ ] homepage: empty `<title></title>` on homepage
- [ ] homepage: empty content for description `<meta name="description" content="">`
- [ ] homepage: empty name for og:name `<meta property="og:site_name" content=""/>`
- [ ] homepage :  undefined og:url `<meta property="og:url" content="undefined/"/>`
- [ ] for now remove *twitter:creator* & *twitter:site* `<meta name="twitter:creator" content="@????"/><meta name="twitter:site" content="@????"/>`
- [ ] remove canonical url `<link rel="canonical" href="undefined/" itemprop="url"/>`
- [ ] 404 NOT FOUND for RSS feeds links:

```html
<link rel="alternate" type="application/rss+xml" title="Feed for articles only" href="/feeds/articles.xml"/>
<link rel="alternate" type="application/rss+xml" title="Feed for links only" href="/feeds/links.xml"/>
```

Check those metas : 

```html
<link rel="pingback" href=""/>
<link rel="webmention" href=""/>
```

---

On post detail page:

- [ ]  undefined base url
```html
<link rel="canonical" href="undefined/post/la-mise-en-forme-avec-fireblog/" itemprop="url"/>
  | <meta property="og:url" content="undefined/post/la-mise-en-forme-avec-fireblog/"/>
```
- [ ] **missing all og:xxx & twitter:xxx tags**

**Comment by bertrandkeller** [comment]
J'ai envoyé quelques modifications, mais je crois que cette partie est un peu touchy. Demande d'avoir des paramètres de config quelque part, de les vérifier…
