### ISSUE TITLE
Souci feed.xml : > Output conflict: multiple input files are writing to `_site/feed.xml`. Use distinct `permalink` values to resolve this conflict.

### ISSUE THREAD

**Issue by yann-yinn** [fireblogcms/eleventy-starter-fireblog#6]
reproduction:

- installation en local (voir README)
- changer la variable de graphql endpoint pour un autre fireblog que celui de démo
- `npm run eleventy:watch`

Le message d'erreur indique une erreur qui n'a guère de sens ...

```
Problem writing Eleventy templates: (more in DEBUG output)
> Output conflict: multiple input files are writing to `_site/feed.xml`. Use distinct `permalink` values to resolve this conflict.
  1. ./post/feed.njk
  2. ./post/feed.njk
```

![image](https://user-images.githubusercontent.com/335495/83570772-eb1b5a00-a526-11ea-9a37-20a8f3c2c4c0.png)

**Comment by bertrandkeller** [comment]
C'est pas un problème de `size`, du coup ?

**Comment by yann-yinn** [comment]
Je n'ai plus le souci, je suppose grâce à #13 ?
